const products = [
    {
        _id: '1',
        name: 'Speaker',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    },
    {
        _id: '2',
        name: 'Head Phone',
        image: '',
        description: 'This is a dummy description',
        brand: 'Unknown',
        category: 'Gadgets',
        price: 99.99,
        countInStock: 10,
        rating: 4.5,
        numberReviews: 12,
    }
]

export default products